### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by Rohith-28** [s-KaiNet/node-sp-auth#112]
C:\Users\css130982\Desktop\node\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:148
            throw new Error(securityTokenResponse.toString());
                  ^

Error: <S:Fault>
  <S:Code>
    <S:Value>S:Sender</S:Value>
    <S:Subcode>
      <S:Value>wst:FailedAuthentication</S:Value>
    </S:Subcode>
  </S:Code>
  <S:Reason>
    <S:Text xml:lang="en-US">Authentication Failure</S:Text>
  </S:Reason>
  <S:Detail>
    <psf:error xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault">
      <psf:value>0x800434D4</psf:value>
      <psf:internalerror>
        <psf:code>0x800434D4</psf:code>
        <psf:text>AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access &apos;&apos;.</psf:text>
      </psf:internalerror>
    </psf:error>
  </S:Detail>
</S:Fault>
    at OnlineUserCredentials.postToken (C:\Users\css130982\Desktop\node\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:148:19)
    at C:\Users\css130982\Desktop\node\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:48:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Please help me to solve this error

**Comment by koltyakov** [comment]
Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access

**Comment by Rohith-28** [comment]
Thanks and if there is any possibilty to get xlsx data

**Comment by Rohith-28** [comment]
i want to get the data from xlsx file without downloading it to local please help me to solve this issue
