### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED error

### ISSUE THREAD

**Issue by cardin** [s-KaiNet/node-sp-auth#118]
I ran into a ERR_OSSL_EVP_UNSUPPORTED error.

My setup details are as follows:
* Windows 2016 Server
* Node 18.9.0

The stacktrace is:
```
{
   stack: 'Error: Unexpected error during http fetch! Error: error:0308010C:digital envelope routines::unsupported\n' +
      '   at new Hash (node:internal/crypto/hash:71:19)\n' +
      '   at Object.createHash (node:crypto:133:10)\n' +
      '   at Object.createNTLMHash (....\\node_modules\\node-ntlm-client\\lib\\hash.js:77:22)\n' +
      '   at Object.createType3Message (...\\node_modules\\node-ntlm-client\\lib\\ntlm.js:213:23)\n' +
      '   at ...\\node_modules\\node-sp-auth\\lib\src\\auth\\resolvers\\OnpremiseUserCredentials.js:41:35\n' +
      ....
      " opensslErrorStack: ['error:03000086:digital envelope routines::initialization error' ],\n" +
      " library: 'digital envelope routines',\n" +
      " reason: 'unsupported',\n" +
      " code: 'ERR_OSSL_EVP_UNSUPPORTED'\n" +
      '}\n'
}
```

Adding a NODE_OPTIONS env flag `export NODE_OPTIONS=--openssl-legacy-provider` as per https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported seemed to remove the error.

**Comment by davea38** [comment]
I am getting this as well - Node v18 is the current LTS version so it'd be great to get this fixed (the openssl-legacy-provider env var doesn't fix all of the errors)

**Comment by zubayed2008** [comment]
I am also having this issue. Is there any chance  to update this package so that the current version of nodejs which has openssl 3.0.10+quic support this library.
