### ISSUE TITLE
node-sp-auth not working with SharePoint online ADFS 

### ISSUE THREAD

**Issue by MPalsodkar** [s-KaiNet/node-sp-auth#34]
Below is the code I am trying to execute

spauth.getAuth('https://domain.sharepoint.com/sites/devs/', {
      username: '[userName]',
      password: '[password]'
    })
    .then(data => {
      var headers = data.headers;
      headers['Accept'] = 'application/json;odata=verbose';
      request.get({
        url: 'https://domain.sharepoint.com/sites/devs/_api/web',
        headers: headers,
        json: true
      }).then(response => {
        console.log(response.d.Title);
      });
      
    });

**Comment by s-KaiNet** [comment]
Any errors?

**Comment by MPalsodkar** [comment]
Something went wrong

If the problem persists, contact the site administrator and give them the information in Technical Details.

Technical Details

[SPLoaderError.loadComponentError]:
***Failed to load component "66c238e8-f807-4f9c-8852-9ce96e8af736" (NewWebpartWebPart).
Original error: ***Failed to load entry point from component "66c238e8-f807-4f9c-8852-9ce96e8af736" (NewWebpartWebPart).
Original error: Error loading https://component-id.invalid/66c238e8-f807-4f9c-8852-9ce96e8af736_0.0.1
	https://component-id.invalid/66c238e8-f807-4f9c-8852-9ce96e8af736_0.0.1 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.

***INNERERROR:
***Failed to load entry point from component "66c238e8-f807-4f9c-8852-9ce96e8af736" (NewWebpartWebPart).
Original error: Error loading https://component-id.invalid/66c238e8-f807-4f9c-8852-9ce96e8af736_0.0.1
	https://component-id.invalid/66c238e8-f807-4f9c-8852-9ce96e8af736_0.0.1 did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.
***CALLSTACK:
Error
   at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-02.010/sp-webpart-workbench-assembly_en-us_60b7571493ccbdbf4b75d5c68e6c141c.js:283:15780)
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-02.010/sp-webpart-workbench-assembly_en-us_60b7571493ccbdbf4b75d5c68e6c141c.js:283:15316)
   at t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-02.010/sp-webpart-workbench-assembly_en-us_60b7571493ccbdbf4b75d5c68e6c141c.js:842:36426)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-02.010/sp-webpart-workbench-assembly_en-us_60b7571493ccbdbf4b75d5c68e6c141c.js:842:42131)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-02.010/sp-webpart-workbench-assembly_en-us_60b7571493ccbdbf4b75d5c68e6c141c.js:842:38705)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-02.010/sp-webpart-workbench-assembly_en-us_60b7571493ccbdbf4b75d5c68e6c141c.js:842:11277)
   at T (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-02.010/sp-webpart-workbench-assembly_en-us_60b7571493ccbdbf4b75d5c68e6c141c.js:8:2116)
   at S (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-02.010/sp-webpart-workbench-assembly_en-us_60b7571493ccbdbf4b75d5c68e6c141c.js:8:2232)
   at j (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-02.010/sp-webpart-workbench-assembly_en-us_60b7571493ccbdbf4b75d5c68e6c141c.js:8:2026)
   at g (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-02-02.010/sp-webpart-workbench-assembly_en-us_60b7571493ccbdbf4b75d5c68e6c141c.js:8:1608)

**Comment by s-KaiNet** [comment]
This module is for nodejs execution environment only, it doesn't work in browser (like you're trying to use it).
