### ISSUE TITLE
Working example ?

### ISSUE THREAD

**Issue by NicolasR** [s-KaiNet/node-sp-auth#35]
Hi,

I'm trying to have a working example but i didn't succeed.
I just used the example on readme and always get this error:

```
Unhandled rejection TypeError: callback is not a function
    at Object.parseType2Message (C:\xxx\node_modules\httpntlm\ntlm.js:116:3)
    at request.then (C:\xxx\node_modules\node-sp-auth\lib\src\auth\resolvers\OnpremiseUserCredentials.js:36:33)
    at tryCatcher (C:\xxx\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\xxx\node_modules\bluebird\js\release\promise.js:512:31)
```

Do you have a working example ?

**Comment by s-KaiNet** [comment]
Hi, 
example in readme is absolutely fine. It's an issue with your authentication in SharePoint. I guess you have kerberos, for on-premise sharepoint only ntlm is supported.

**Comment by NicolasR** [comment]
Ok thank you.
