### ISSUE TITLE
Undesired behavior during auth resolution for SPO Add-In 

### ISSUE THREAD

**Issue by Js-Brecht** [s-KaiNet/node-sp-auth#63]
After authentication credentials are collected for Sharepoint Online Add-In Only, when the config is written out, it contains "Online: True".  As a result, because of the process order during the auth resolution, the auth type is **always** returned as Sharepoint Online User credentials.

To recreate, run node, and execute getAuth with add-in only clientId and clientSecret:
```
PS> node -e "
var spAuth = require('node-sp-auth');
spAuth.getAuth('https://<your-sharepoint-domain>.sharepoint.com'); 
"

? SharePoint URL https://<your-sharepoint-domain>.sharepoint.com
? Authentication strategy Add-In Only permissions
? clientId <ClientId>
? clientSecret <ClientSecret>
Unhandled rejection TypeError: Cannot read property 'replace' of undefined
    at new OnlineUserCredentials (D:\dev\Source\node\sp-rest-proxy\node_modules\.registry.npmjs.org\node-sp-auth\2.5.7\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:22:14)
    at Function.resolve (D:\dev\Source\node\sp-rest-proxy\node_modules\.registry.npmjs.org\node-sp-auth\2.5.7\node_modules\node-sp-auth\lib\src\auth\AuthResolverFactory.js:28:20)
    at Promise.resolve.then.then.authOptions (D:\dev\Source\node\sp-rest-proxy\node_modules\.registry.npmjs.org\node-sp-auth\2.5.7\node_modules\node-sp-auth\lib\src\auth\resolvers\FileConfig.js:54:62)
    at tryCatcher (D:\dev\Source\node\sp-rest-proxy\node_modules\.registry.npmjs.org\bluebird\3.5.5\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\dev\Source\node\sp-rest-proxy\node_modules\.registry.npmjs.org\bluebird\3.5.5\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\dev\Source\node\sp-rest-proxy\node_modules\.registry.npmjs.org\bluebird\3.5.5\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\dev\Source\node\sp-rest-proxy\node_modules\.registry.npmjs.org\bluebird\3.5.5\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\dev\Source\node\sp-rest-proxy\node_modules\.registry.npmjs.org\bluebird\3.5.5\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\dev\Source\node\sp-rest-proxy\node_modules\.registry.npmjs.org\bluebird\3.5.5\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\dev\Source\node\sp-rest-proxy\node_modules\.registry.npmjs.org\bluebird\3.5.5\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\dev\Source\node\sp-rest-proxy\node_modules\.registry.npmjs.org\bluebird\3.5.5\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\dev\Source\node\sp-rest-proxy\node_modules\.registry.npmjs.org\bluebird\3.5.5\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

The issue lies in the [AuthResolverFactory](https://github.com/s-KaiNet/node-sp-auth/blob/master/src/auth/AuthResolverFactory.ts#L14) class

The process order hits [isUserCredentialsOnline](https://github.com/s-KaiNet/node-sp-auth/blob/master/src/auth/AuthResolverFactory.ts#L33) first, which returns true [here](https://github.com/s-KaiNet/node-sp-auth/blob/master/src/auth/IAuthOptions.ts#L76) because the online property is set.

The way I've worked around it is like so

```
  if ((T as IUserCredentials).username !== undefined && (T as IUserCredentials).online) {
    return true;
  }
```

But I feel like the config is malformed in the first place.  Typescript interface for the Online Add-In Only is like this:
```
export interface IBasicOAuthOption {
  clientId: string;
}

export interface IOnlineAddinCredentials extends IBasicOAuthOption {
  clientSecret: string;
  realm?: string;
}
```
No 'online' property defined for OnlineAddinCredentials.  Perhaps node-sp-auth-config is not processing add-in credentials correctly.  This is as far as I've been willing to look, though.

**Comment by s-KaiNet** [comment]
`online` property is used only in case of user credentials because it's not possible to correctly identify if we're working with SharePoint Online or on-prem site based on the url and username. For add-in only permissions it's possible because on-prem add-in permission doesn't have `clientSecret` property. This is the reason why `online` was added for user credentials only.     

In theory we can fix it here using your proposal or in `node-sp-auth-config` repo. It looks like fixing `node-sp-auth-config` is more valid here, because `online` property isn't supported for add-in permissions based on interfaces. @koltyakov 	could you please take a look? Is it difficult to make a fix?

**Comment by koltyakov** [comment]
Perhaps we should move this validation onside [isOnPremUrl](https://github.com/s-KaiNet/node-sp-auth/blob/master/src/auth/IAuthOptions.ts#L61). 

However, I can exclude `online` flag for AddIns as they have their own fingerprint to distinguish online and on-prem even fo O365 dedicated when URL pattern is different from .sharepoint.*.

**Comment by koltyakov** [comment]
As it's obviously a result of recent changes in node-sp-auth-config, let me better align the fix on `-config` side. @Myrlin1 can you try v2.6.7 which I just published? It should not add `online` flag for `OnlineAddinCredentials`.

**Comment by Myrlin1** [comment]
Confirmed: it works

**Comment by s-KaiNet** [comment]
Thank you all for cooperation :)
